import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "@/components/ui/button";
import { role } from "@/constants/role.constant";
import { useUserInfoQuery } from "@/redux/features/auth/auth.api";
import { motion } from "framer-motion";
import { AddRideModal } from "../rides/AddRideModal";
export default function CTASection() {
    const { data, isLoading } = useUserInfoQuery(undefined);
    const userRole = data?.data?.role;
    if (isLoading) {
        return _jsx("div", { children: "Loading...." });
    }
    const heading = "Ready to Start Your Journey?";
    const subText = "Book your ride in just a few clicks and enjoy a safe, comfortable journey.";
    return (_jsx("section", { className: "py-20 bg-background mb-5 text-foreground", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 text-center", children: [_jsx(motion.h2, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.8 }, className: "text-3xl md:text-5xl font-bold mb-6 text-foreground", children: heading }), _jsx(motion.p, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.8, delay: 0.2 }, className: "text-lg md:text-xl mb-8 text-foreground opacity-80", children: subText }), _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.8, delay: 0.4 }, className: "flex justify-center gap-4 flex-wrap", children: [!userRole && (_jsxs(_Fragment, { children: [_jsx(Button, { size: "lg", className: "rounded-2xl shadow-lg bg-primary hover:bg-primary/90 text-primary-foreground font-bold cursor-pointer transition-all transform hover:scale-105", children: "Request a Ride" }), _jsx(Button, { size: "lg", variant: "outline", className: "rounded-2xl border-primary text-primary hover:bg-primary/10 cursor-pointer font-bold", onClick: () => (window.location.href = "/register"), children: "Sign Up Now" })] })), userRole === role.RIDER && (_jsxs(_Fragment, { children: [_jsx(AddRideModal, { context: "Request a Ride", size: "lg", className: "rounded-2xl shadow-lg bg-primary hover:bg-primary/90 text-primary-foreground font-bold cursor-pointer transition-all transform hover:scale-105" }), _jsx(Button, { size: "lg", variant: "outline", className: "rounded-2xl border-primary text-primary hover:bg-primary/10 cursor-pointer font-bold", onClick: () => (window.location.href = "/rider/profile"), children: "Become a Driver" })] })), userRole === role.DRIVER && (_jsxs(_Fragment, { children: [_jsx(Button, { size: "lg", className: "rounded-2xl shadow-lg bg-primary hover:bg-primary/90 text-primary-foreground font-bold cursor-pointer transition-all transform hover:scale-105", onClick: () => (window.location.href = "/driver/profile"), children: "Go Online" }), _jsx(Button, { size: "lg", variant: "outline", className: "rounded-2xl border-primary text-primary hover:bg-primary/10 cursor-pointer font-bold", onClick: () => (window.location.href = "/driver/profile"), children: "Become a Rider" })] })), userRole === role.ADMIN && (_jsx(Button, { size: "lg", className: "rounded-2xl shadow-lg bg-primary hover:bg-primary/90 text-primary-foreground font-bold cursor-pointer transition-all transform hover:scale-105", onClick: () => (window.location.href = "/admin"), children: "Manage Dashboard" }))] })] }) }));
}
