import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { Provider as ReduxProvider } from "react-redux";
import { RouterProvider } from "react-router";
import { Toaster } from "sonner";
import "./index.css";
import { ThemeProvider } from "./providers/theme-provider";
import { store } from "./redux/store";
import { router } from "./routes/index";
createRoot(document.getElementById("root")).render(_jsx(StrictMode, { children: _jsx(ReduxProvider, { store: store, children: _jsxs(ThemeProvider, { defaultTheme: "system", storageKey: "vite-ui-theme", children: [_jsx(RouterProvider, { router: router }), _jsx(Toaster, { richColors: true })] }) }) }));
